# Generated by Django 4.1.7 on 2023-04-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_monthlysummary_goal_budgetusers_budgetitems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetusers',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='budgetusers',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
