# Generated by Django 4.1.7 on 2023-04-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accounts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
