# Generated by Django 4.1.7 on 2023-04-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_account_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetusers',
            name='savings_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
