# Generated by Django 4.1.7 on 2023-04-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=400, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, choices=[('Massachusetts', 'Massachusetts'), ('Maine', 'Maine')], max_length=200, null=True)),
                ('bio', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_photo', models.ImageField(upload_to='profileImage/')),
                ('health_insurance', models.BooleanField(blank=True, null=True)),
                ('life_insurance', models.BooleanField(blank=True, null=True)),
                ('disability', models.BooleanField(blank=True, null=True)),
                ('series6', models.BooleanField(blank=True, null=True)),
                ('series63', models.BooleanField(blank=True, null=True)),
                ('series65', models.BooleanField(blank=True, null=True)),
                ('series67', models.BooleanField(blank=True, null=True)),
                ('series7', models.BooleanField(blank=True, null=True)),
                ('sie', models.BooleanField(blank=True, null=True)),
                ('cfp', models.BooleanField(blank=True, null=True)),
                ('cpa', models.BooleanField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=200, null=True)),
                ('major', models.CharField(blank=True, choices=[('Massachusetts', 'Massachusetts'), ('Maine', 'Maine')], max_length=200, null=True)),
                ('start_date', models.CharField(blank=True, max_length=200, null=True)),
                ('end_date', models.CharField(blank=True, max_length=200, null=True)),
                ('interest1', models.CharField(blank=True, max_length=200, null=True)),
                ('interest2', models.CharField(blank=True, max_length=200, null=True)),
                ('interest3', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
